export const AUTHENTICATION_REQUEST="AUTHENTICATION_REQUEST";
export const AUTHENTICATION_SUCCESS="AUTHENTICATION_SUCCESS";
export const AUTHENTICATION_FAILURE="AUTHENTICATION_FAILURE";


export const LOGOUT_REQUEST="LOGOUT_REQUEST";
export const LOGOUT_SUCCESS="LOGOUT_SUCCESS";
export const LOGOUT_FAILURE="LOGOUT_FAILURE";

export const MAKEUP_REQUEST="MAKEUP_REQUEST";
export const MAKEUP_SUCCESS="MAKEUP_SUCCESS";
export const MAKEUP_FAILURE="MAKEUP_FAILURE";

// created by pallavee

export const ADDTOCART_REQUEST="ADDTOCART_REQUEST";
export const ADDTOCART_SUCCESS="ADDTOCART_SUCCESS";
export const ADDTOCART_FAILURE="ADDTOCART_FAILURE";

export const GETCARTDATA_REQUEST= "GETCARTDATA_REQUEST";
export const GETCARTDATA_SUCCESS= "GETCARTDATA_SUCCESS";
export const GETCARTDATA_FAILURE= "GETCARTDATA_FAILURE";

export const UPDATECARTDATA_REQUEST= "UPDATECARTDATA_REQUEST";
export const UPDATECARTDATA_SUCCESS= "UPDATECARTDATA_SUCCESS";
export const UPDATECARTDATA_FAILURE= "UPDATECARTDATA_FAILURE";

export const STOREFINALPRICE_SUCCESS= "STOREFINALPRICE_SUCCESS";